version: '3'
services:
  message-server:
    container_name: message-server
    build:
      context: message-server
      dockerfile: Dockerfile
    image: rate_limiting:latest
    ports:
      - "8080:8080"
    networks:
      - spring-cloud-network
  prometheus:
    image: "prom/prometheus"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    container_name: prometheus
    networks:
      - spring-cloud-network
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge